# Generated by Django 3.2.3 on 2023-08-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тэг')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг тэга')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='Цветовой HEX-код')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ('name',),
            },
        ),
    ]
