# Generated by Django 3.2.3 on 2023-08-11 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230811_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='RecipeIngredient',
        ),
    ]
